### ISSUE TITLE
PyPI release?

### ISSUE THREAD

**Issue by strichter** [bradbase/xlcalculator#1]
Are you planning to release the package on PyPI, otherwise it is pretty useless to people.

**Comment by bradbase** [comment]
Hi @strichter,

Thanks for raising the first issue :D

It has been released on PyPi a few hours ago. Until yesterday (my time) it didn't work well enough out-of-the-box. Being a 0.0.x beta it's still likely to have problems, but at least there's evidence that it's able to do what is claimed in some circumstances without "holding your tongue the right way".

**Comment by bradbase** [comment]
Ensure you get version 0.0.3b else evaluator uses a cached value for a cell regardless of set_cell_value()

**Comment by strichter** [comment]
Thanks.
