### ISSUE TITLE
Undefined variable `start_row`.

### ISSUE THREAD

**Issue by strichter** [bradbase/xlcalculator#11]
https://github.com/bradbase/xlcalculator/blob/9d36d52ab91a2139d31081de60dc7995ce77b560/xlcalculator/xlcalculator_types/range.py#L113

Since you do not have an `else` in an expression above `start_row` can be undefined, which happens when the start list is empty, like when you do not specify a row in your range. (Valid for named ranges, where I use it all the time.)

**Comment by bradbase** [comment]
This sounds like bug #8 presenting in defined names.

Is there a spreadsheet or two you are able to share with examples of Excel techniques you use?

I genuinely appreciate your feedback. In saying that I have looked you up on LinkedIn and I feel bad dragging you through my coding inadequacies one line at a time. There's no doubt xlcalculator needs to be able to handle the way you use Excel. I'm thinking having an Excel file I can code against which exemplifies some common techniques that you use might be helpful on a number of fronts. I'm also interested to see the architecture in which you're expecting to use xlcalculator, but simply getting it working is a much higher priority.

**Comment by strichter** [comment]
I sent you an E-mail earlier with a sample file and a sample program that exercises it. If you have not gotten it, send me an E-mail to stephan.richter@gmail.com
