### ISSUE TITLE
please set the required yearfrac version to >=0.4.4

### ISSUE THREAD

**Issue by ulf1** [bradbase/xlcalculator#18]
One of your users (@Octanny) had problems to install the `yearfrac` dependency due to the `six` package.
https://github.com/kmedian/yearfrac/issues/14

I removed the `six` completely, and thus, the backward compatibility to Python2. 

Please update the version to 

- `yearfrac>=0.4.4`
- or  `yearfrac==0.4.*`  (i.e. the latest 0.4.something version)

Related files:
- https://github.com/bradbase/xlcalculator/blob/9f3b17aeb0f16d3c505494b34e0e44df4a43123d/setup.py#L50
- https://github.com/bradbase/xlcalculator/blob/master/requirements.txt#L36

**Comment by bradbase** [comment]
Thanks @ulf1 

I'll get a release out shortly.
