### ISSUE TITLE
read_excel_file() should not be a static method.

### ISSUE THREAD

**Issue by strichter** [bradbase/xlcalculator#3]
When I overwrite read_excel_file() to fix the abspath() issue I also had to overwrite `read_and_aprse_archive()` since it calls `ModelCompiler.read_excel_file(file_name)`. Just make `read_excel_file()` a proper method.

**Comment by bradbase** [comment]
Please try v0.0.6b

**Comment by strichter** [comment]
You need to make it a proper method not a class method. This way you can call `self.read_excel_file()` in `read_and_parse_archive()` instead of `ModelCompiler.read_excel_file()`.
