### ISSUE TITLE
Case insensitivity issues with Text comparison (IF, SUMIFS, etc)

### ISSUE THREAD

**Issue by Adanteh** [bradbase/xlcalculator#38]
Excel evaluates the string comparisons for most of the IF functions as insensitive, but currently it does case sensitive check.

Following file will cause SUMIFS tests to fail if used in resources: [SUMIFS.xlsx](https://github.com/bradbase/xlcalculator/files/5649178/SUMIFS.xlsx)

**Comment by bradbase** [comment]
@Adanteh Please confirm whether draft PR #39 addresses this issue report.
