### ISSUE TITLE
Ranges do not support worksheet names with spaces.

### ISSUE THREAD

**Issue by strichter** [bradbase/xlcalculator#9]
The problem is that all white space gets removed from an address in `XLRange.cell_address_infill()`, line 79. this is a pretty big show stopper for me.

**Comment by bradbase** [comment]
Do the range addresses begin with a space?

**Comment by strichter** [comment]
No, they contain spaces though: "Foo Bar"

**Comment by bradbase** [comment]
OK. I have changed replace to strip.
